version: "3.8"

services:
  db:
    image: mysql:9.3.0
    container_name: todo_mysql
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3307:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 13s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: sh -c "./wait-for-it.sh db:3306 -- node src/infrastructure/http/server.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    restart: always
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  todo-mysql-data:
